default: &default
  adapter: postgresql
  pool: 5
  encoding: utf8
  timeout: 5000

development:
  <<: *default
  host: "localhost"
  database: ludotecapp_development

test:
  <<: *default
  host: "localhost"
  database: ludotecapp_test
  allow_concurrency: true
  min_messages: error

production:
  adapter: postgresql
  pool: 5
  encoding: utf8
  database: ludotecapp_production
  username: ludotecapp
  password: <%= ENV['LUDOTECAPP_DATABASE_PASSWORD'] %>
